# -*- coding: utf-8 -*-
"""Vicky_Practical_exam_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZn_B-tg5Vkns10mQ5rRmhJHgfM4hO9t

### **1. Repository Setup**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/karpathy/nanoGPT
# %cd nanoGPT
!pip install tiktoken requests

"""###**2. Train the Shakespeare Character-level Model**"""

# Prepare the dataset
!python data/shakespeare_char/prepare.py

# Train BabyGPT (default settings)
# limit max_iters for a quick initial run
!python train.py config/train_shakespeare_char.py --max_iters=1000 --device=cuda

# Generate samples and save the first 5 lines to your report.md
!python sample.py --out_dir=out-shakespeare-char > shakespeare_output.txt
!head -n 5 shakespeare_output.txt

# For Task 2 - write to report.md explicitly:
with open('report.md', 'w') as f:
    f.write("# SEEM3650 Practical Exam Report\n\n")
    f.write("## Task 2: Shakespeare Character-level Model Samples\n")
    f.write("First 5 lines of generated output:\n```\n")
    with open('shakespeare_output.txt', 'r') as samples:
        lines = samples.readlines()[:5]
        f.writelines(lines)
    f.write("```\n\n")

"""### **3.1 Remainder 2: Layers = 7, Heads ∈ {2, 3, 5, 7}**
XYZ = 866
"""

import matplotlib.pyplot as plt
import subprocess
import re
import os

# Create figures directory
os.makedirs('figures', exist_ok=True)

# Requirement for XYZ mod 4 = 2
fixed_layers = 7
heads_to_test = [2, 3, 5, 7]
results = {}
consistent_iters = 500

print(f"Starting Debugged Architecture Exploration: Layers={fixed_layers}")

for h in heads_to_test:
    print(f"\n>>> Training Run: Layers={fixed_layers}, Heads={h}...")

    # 1. n_embd=420 (divisible by 2, 3, 5, 7)
    # 2. batch_size=32 (prevents OOM crashes)
    cmd = (f"python train.py config/train_shakespeare_char.py "
           f"--device=cuda --compile=False --max_iters={consistent_iters} "
           f"--n_layer={fixed_layers} --n_head={h} --n_embd=420 "
           f"--batch_size=32 --eval_interval={consistent_iters}")

    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

    final_val_loss = None
    for line in process.stdout:
        # Print lines containing 'step' or 'loss' to monitor progress
        if "step" in line or "loss" in line:
            print(line.strip())

        if "val loss" in line:
            match = re.findall(r"val loss ([\d.]+)", line)
            if match:
                final_val_loss = float(match[-1])

    process.wait()

    if final_val_loss is None:
        print(f"Error: Training crashed for Head {h}. Check GPU memory.")
    else:
        results[h] = final_val_loss
        print(f"Finished! Final Val Loss for {h} heads: {final_val_loss}")

"""### **3.2 Visualization**"""

if results:
    plt.figure(figsize=(8, 5))
    plt.plot(list(results.keys()), list(results.values()), marker='o', color='darkorange')
    plt.title(f'Performance Comparison (Layers=7, n_embd=420)')
    plt.xlabel('Number of Attention Heads')
    plt.ylabel(f'Validation Loss (Iteration {consistent_iters})')
    plt.grid(True, linestyle='--')
    plt.xticks(heads_to_test)
    plt.savefig('figures/heads_vs_loss.png')
    plt.show()

    print("\nTask 3 Summary for report.md:")
    for h, loss in results.items():
        print(f"Heads: {h} | Val Loss: {loss}")
else:
    print("No results to plot. Please ensure your GPU runtime is active.")

# For Task 3 - add to report.md:
with open('report.md', 'a') as f:
    f.write("## Task 3: Model Architecture Exploration\n")
    f.write(f"Configuration: XYZ mod 4 = 2\n")
    f.write(f"Fixed parameter: Layers = {fixed_layers}\n")
    f.write("Results:\n")
    for h, loss in results.items():
        f.write(f"- Heads={h}: Val Loss={loss:.4f}\n")

    best_heads = min(results, key=results.get)
    best_loss = results[best_heads]
    f.write(f"\n**Best configuration:** Layers={fixed_layers}, Heads={best_heads}\n")
    f.write(f"**Lowest validation loss:** {best_loss:.4f}\n")

"""### **4. Training BabyGPT for Code Generation**"""

# Commented out IPython magic to ensure Python compatibility.
import os

# 1. Create the new dataset directory by duplicating shakespeare_char structure
!mkdir -p data/code_generation
!cp data/shakespeare_char/prepare.py data/code_generation/

# 2. Download open-source C code (Linux kernel and Redis)
# Combine multiple files to ensure we hit the 100k token mark
urls = [
    "https://raw.githubusercontent.com/torvalds/linux/master/kernel/sched/core.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/kernel/fork.c",
    "https://raw.githubusercontent.com/redis/redis/unstable/src/server.c",
    "https://raw.githubusercontent.com/redis/redis/unstable/src/debug.c"
]

with open('data/code_generation/input.txt', 'w') as f:
    for url in urls:
        import requests
        code = requests.get(url).text
        f.write(code + "\n\n")

# 3. Run the prepare.py script
# %cd data/code_generation
!python prepare.py
# %cd ../..

# 4. Report token count
import numpy as np
train_bin = np.memmap('data/code_generation/train.bin', dtype=np.uint16, mode='r')
val_bin = np.memmap('data/code_generation/val.bin', dtype=np.uint16, mode='r')
total_tokens = len(train_bin) + len(val_bin)
print(f"\nTOTAL TOKENS COMPUTED: {total_tokens}")

config_content = f"""
# Configuration for Training BabyGPT on C Code
dataset = 'code_generation'
out_dir = 'out-code-generation'
eval_interval = 250
eval_iters = 200
log_interval = 10

# Model architecture (Consistent with your Task 3 best findings)
n_layer = 7
n_head = 6  # Use your best head count from Task 3
n_embd = 420
block_size = 256

# Training settings
batch_size = 32
gradient_accumulation_steps = 1
max_iters = 1000
learning_rate = 1e-3
lr_decay_iters = 1000
min_lr = 1e-4
beta2 = 0.99
warmup_iters = 100

device = 'cuda'
compile = False
"""

with open('config/train_code_generation.py', 'w') as f:
    f.write(config_content)

# 1. Train the model
!python train.py config/train_code_generation.py

# 2. Generate sample outputs
!python sample.py --out_dir=out-code-generation --num_samples=1 --max_new_tokens=1000 > code_samples.txt

# 3. Display the first 20 lines for the report
print("\n--- Task4：FIRST 20 LINES OF GENERATED CODE ---")
with open('code_samples.txt', 'r') as f:
    lines = f.readlines()
    for line in lines[:20]:
        print(line.strip())

# Append Task 4 results to report.md
with open('code_samples.txt', 'r') as f:
    all_lines = f.readlines()
first_20_lines = all_lines[:20]
with open('report.md', 'a') as f:
    f.write("\n### First 20 Lines of Generated Code Samples\n")
    f.write("```\n")
    for line in first_20_lines:
        f.write(line.rstrip() + '\n')  # rstrip to avoid double newlines
    f.write("```\n\n")

    f.write("### Favorite Generated Code Snippet\n")
    f.write("The most coherent/interesting snippet from the generated code:\n")
    f.write("```c\n")

    # Option 1: Show a specific interesting portion (e.g., lines 5-15)
    if len(first_20_lines) >= 10:
        interesting_snippet = first_20_lines[5:15]  # Adjust indices as needed
        for line in interesting_snippet:
            f.write(line.rstrip() + '\n')
    else:
        # If fewer than 10 lines, just show everything
        for line in first_20_lines:
            f.write(line.rstrip() + '\n')

    f.write("```\n")

print(f"\nSaved first {len(first_20_lines)} lines of code samples to report.md")
print("\n--- First 20 lines preview ---")
for i, line in enumerate(first_20_lines, 1):
    print(f"{i:2d}: {line.rstrip()}")